### ISSUE TITLE
5장 웹 서버 질문

### ISSUE THREAD

**Issue by jeuxdeau** [jeuxdeau/http-the-definitive-guide#15]
# 웹 서버
### 투표 선정
- ~IETF ident에서 IETF란 무엇인가?~ => 의미 없는 질문이니 하지 말자..
- 서버사이드 인클루드란 무엇인가?
- "웹 서버"의 여러 가지 의미에 대해 정리해 보자. (Ex. 웹 서버 소프트웨어, 하드웨어, was...)
- 유형 협상을 통해 MIME type이 결정되는 자세한 과정과 주로 사용되는 상황은?

### 탈락
- (126p) 웹 서버를 내장시키게 한 마이크로소프트의 기적이 뭐야?
- url 증강(145p)에서 말하는 "문맥 정보"의 예시?
- 유명한 웹 서버들이 차용한 아키텍쳐와 각 서버들의 성능 차이(tps, max connection 등등)
- 웹 서버들은 각각의 웹 서버 입/출력 아키텍쳐를 실제로 어떻게 구현했을까?
- CGI와 비교해 액티브 서버 페이지나 자바 서블릿이 가지는 장점
- 가상 호스팅에서 각 호스트별로 서버 리소스도 분리해 사용할 수 있나?(메모리, 대역폭, CPU)

### 오프라인
TBD

## 공지
- 월요일 서현에서 합니다 (명근 파티 예정)
- 저 한국에 못갔으니까 월요일에 안나타나면 죽은줄 아셔요 ㅎㅎ

**Comment by digression99** [comment]
## 오프라인 질문

* 역방향 디엔에스는 원래 디엔에스와 같은건가..?
* 모든 클라이언트가 호스트명이 있는가?
* Ident 사용자 이름과 호스트 명은 같은 것인가? 다른 것인가?
* 문맥 정보를 포함하기 위해 재 작성된 url 로 다이렉트 (oauth??)
* 상태 정보를 내포한 새 url을 생성하고 사용자를 리다이렉트 fat url / o
* 클라이언트가 다르면 Hostname이 다른 것일까

**Comment by jeuxdeau** [comment]
깃북 동기화 안되는 이슈~

**Comment by digression99** [comment]
실습도 해보고 싶다~

**Comment by jeuxdeau** [comment]
우빈:앞123
명근:뒤45(6는2와같은듯)

**Comment by mgcation** [comment]
## 오프라인 질문 답변
### 문맥 정보를 포함하기 위해 재 작성된 url 로 다이렉트
> 4, 5 질문이 말하고자하는 바가 같음.

해당 내용은 11.5 절에도 포함되어 있는 내용입니다.

특정한 웹사이트가 사용하는 방법으로, 널리 사용되는 표준은 아닌듯 합니다.
서버는 클라이언트와의 문맥 정보를 결정하는 `상태 정보`를 만들어 url 의 처음이나 끝에 포함합니다.
유저는 사이트를 돌아다니면서 이 상태정보가 유지되도록 하는 동적으로 생성된 하이퍼링크를 사용합니다.

![image](https://user-images.githubusercontent.com/20185848/69180243-4d46db80-0b50-11ea-972f-bf17d9e8a119.png)

위 그림을 보면 모두 같은 식별번호가 링크에 삽입되어 있는데 현재 문맥 정보를 이어가기 위해서입니다. (클라이언트에서 만료되는 쿠키와는 다르게 서버에서 만료하지 않는 이상 어느 클라이언트든 같은 문맥을 이어갈 수 있는 url)

처음 방문 시에는 fat URL 을 사용하도록 강제하기 위해 유저식별정보를 만들고, 이를 이용한 url 로 강제 리디렉션을 시킵니다.
이에 발생하는 문제점과 자세한 설명에 대해서는 책 p.304 또는 [pdf.en](http://www.staroceans.org/e-book/O'Reilly%20-%20HTTP%20-%20The%20Definitive%20Guide.pdf) p.245 참고 바람.
