### ISSUE TITLE
7장 캐시 질문

### ISSUE THREAD

**Issue by mgcation** [jeuxdeau/http-the-definitive-guide#22]
# 캐시
### 투표 선정
- `캐시망에서 형제 캐시사이 인터넷 트랜짓을 허용하지 않는다`의 의미?
- 캐시 서버는 캐싱된 응답의 메타데이터를 어떻게 관리할까?
- HTTPS 요청도 인터셉트 프락시가 가로채서 캐싱해줄 수 있나?
- 같은 캐시망 내에서 형제 캐시가 데이터 있음을 어떻게 알 수 있을까?

### 탈락 (2위)
- 요청/응답에 따라 다른 Cache-control 헤더에 대해 알아보기
- `CGI gateway`가 무엇인지 자세히 알아보기
- 비표준 캐시 헤더에 대해 더 알아보기 (x-cache, x-cache-status, ...) -> `위키피디아 헤더에서 발견하였음.`
- etag의 단점? (거의 안쓰이는 듯 한데 왜 안쓸까?)
- 프락시 연쇄는 왜 성능저하를 부를까?
- `must-revalidate vs no-cache` 무슨 차이가 있는걸까? revalidate 후에는 사본만 계속 제공하나?

### 탈락
- 캐시 관련 헤더들의 처리에 있어서 우선순위가 존재할까? (Cache-Control, Expires, ETag, ...)
- 캐시 관련 헤더가 엄청 많이 포함되어 있으면 캐시 서버는 이 모든 것을 굳이 고려해야 되나? 아니면 하나만 보고 판단할 수 있나?

## 이번 주 공지
- 월요일 7시 서현 ^_^

**Comment by jeuxdeau** [comment]
@digression99 일띡 숙제 🥇 

1. 이번 주 질문에 대한 본인 답변 올리기
2. 오프라인 질문 정리한 것 올리기
3. (진행 방식에 대해) 회의한 내용 올리기 <= 이건 내가 할까?
4. 강의안 작성 앞으로 어떻게 할 것인지...

**Comment by digression99** [comment]
오프라인 질문들

Q. 캐시는 장애가 안날까? 캐시가 장애나면 어떻게 될까?

A. 자훈 - 보통 하나의 캐시망에 거치는 캐시가 1대 이상 있어, 하나의 캐시가 죽더라도 다른 캐시로 연결되어 fault tolerant한 구조를 만들 것.

Q. 객체와 문서는 다를까?

A. 우빈 - 응답 객체 하나의 단위로 문서 하나와 동일하지 않을까.

Q. 캐시가 사본이 신선하다고 어떻게 임시로 표시할까?

A. 자훈 - Expires 헤더를 갱신하지 않을까. Origin server에서 만료 시간을 갱신하여 내려줄 것이다.

A. 일식 - Date 헤더를 수정할 줄 알았는데 아니다..

Q. 고성능 서버는 왜 캐시 프락시 연쇄가 문제되지 않을까?

A. 자훈 - 아마 그냥 하드웨어 성능이 좋아져서 그런 게 아닐까.

Q. 캐시는 문서 재검사 전에는 서버가 죽어도 정상적인 응답을 내리는가?

A. 우빈(정리) - 재검사 전에는 신선하므로 정상 응답을 내리고, 재검사때 서버가 죽었는지를 알 수 있으므로 그때 비정상 응답을 내릴 것.

Q. 캐시망에서는 데이터가 여러 곳에 중복되어 저장될 수 있을까? sibling cache가 다른 sibling cache를 참조하는 경우 같은 캐시 클러스터 안에 있는 것일까? 같은 캐시 클러스터일 경우 중복된 데이터를 저장하지 않을까?

A. 우빈 - ICP(internet cache protocol)에 따르면 중간 프록시 서버가 여러 sibling cache 에 질의를 던져 결과를 받는다. 이때 데이터를 받은 sibling cache는 사본을 중복 저장하게 된다. (p.554)

Q. 중간자 공격과 인터셉트 프락시의 패킷 체크는 무엇이 다를까? https일 경우 인터셉트 프락시에서도 보안이 유지될까?

**Comment by jeuxdeau** [comment]
A. 명근 - 프락시 서버도 공인된 기관에서 인증서 받기 때문에, https 커넥션 맺음. 패킷 까볼 수 있음. (명근의 충격)

일식 - 본문의 내용을 암호화하라.
