### ISSUE TITLE
8장 통합점:게이트웨이,터널,릴레이 질문

### ISSUE THREAD

**Issue by digression99** [jeuxdeau/http-the-definitive-guide#26]
# 통합점:게이트웨이,터널,릴레이
### 일식
p.198

- server certificate은 어떻게 얻는 것일까?

p.199

- WAS는 사실상 gateway의 역할을 하는 것일까?
- proxy와 gateway의 차이는 양쪽 모두를 http로 말하는가의 차이인가?

p200

- MSIE?

p202

- 애초에 http client에서 https로 보내는 게 아니라면, gateway전에는 안전하지 않은 건가?
- security accelerator gateway는 무엇?

p203

- figure 8-8에서는 아예 요청/응답을 넘겨버리는데, 클라와 서버간 통신의 헤더 등이 유지될 필요가 있는가?

p204

- 언제까지 CGI가 쓰였을까?

p205

- server extension api는 무엇이 있었을까? 지금의 웹 환경과 매칭되는 건 무엇이 있을까?

p206

- web tunnel과 gateway의 차이는 무엇일까?
- CONNECT method는 왜 사용되는가. 다른 방법으로 해결되지 못하는 것일까?

p207

- figure 8-10의 예시에서 직접 서버와 ssl connection을 맺지 않는 이유는 무엇일까. 즉, 이 예시에서 gateway(tunnel endpoint)가 필요한 이유는 무엇일까.
- ssl connection과 tcp connection은 어떻게 다를까.
- ssl과 https는 다를까? 다르다면 어떤 암호화 사용, 어떻게 다를까.

p209

- fig 8-11에서 firewall은 어떤 역할을 하는 것일까?

p210

- x509 certificate?

p211

- fig 8-13의 인증과정을 자세히 이해해보자. - proxy authenticate, proxy authorization은 어떻게 쓰이는걸까.

p212

- relay, tunnel의 차이는 무엇일까.

p213

- nginx는 blind relay를 어떻게 구현할까?
- blind relay는 websocket과는 어떻게 다를까?
- express에서는 keep alive를 어떻게 다룰까?

## 이번 주 공지
- 수요일 강남역 저녁 8시 모임

**Comment by mgcation** [comment]
> \* 표시는 정확하지 않음을 의미

#### 통합점이라고 명명한 이유는 무엇일까? 심오한 의미가 있을까?
ㅁㄹ.. 릴레이는 왜 넣고 프록시는 왜 빼놓고 얘기하는거야..

#### *HTTP/HTTPS 게이트웨이 : 서버측 보안용도 : 서버측 게이트웨이에 들어가기 전 까지는 보안이 안 되는 것은 아닐까? : 어떤 보안에 힘을 쓰려는걸까?

내부망을 HTTPS로 강제하는 것은 도대체 무슨 의미가 있는 걸까? 아무리 찾아도 이해가 안된다.

> 책 후반부에 보면 SSL 터널링에 대해 나오는데 이 경우 비슷한 용도인 것 같다. HTTP 위에 HTTPS 메시지를 올려 통신하지만 HTTP/HTTPS 게이트웨이에 비해 클라이언트와 원서버가 직접 SSL 커넥션을 이룰 수 있어 좋다는 내용.

그렇다면 HTTP/HTTPS 게이트웨이의 경우에도 80번 포트만 허용하는 리버스프록시(게이트웨이) 에 통신하되 내부적으로는 SSL 처리를 하는 것일까?

#### *리소스 게이트웨이, CGI, WAS, 웹서버 등 용어가 혼동되는 것 같다. 헷갈린다.
##### 웹서버
nginx 등
정적으로 정해진 프로그램을 직접 실행한다.

##### WAS
tomcat 등
동적으로 프로그램을 찾아 실행한다.
웹 서버에 어플리케이션(동적으로 돌아가게)이 같이 돌아가는 형태.

##### CGI
동적인 웹 서비스를 위한 표준. 이를 구현한 것이 WAS.
고로, CGI + 웹서버 = WAS

##### 리소스 게이트웨이
http 요청을 받으면 특정 어플리케이션, 프로토콜을 통해 리소스를 받아오는 게이트웨이
고로, WAS, 웹서버 모두 리소스 게이트웨이에 해당한다.

#### 데몬 프로세스가 뭘까? 안쓰면 CGI가 느려지는 이유?

##### 데몬 프로세스
쉽게 말해 백그라운드 프로세스의 일종.

##### CGI 프로세스
CGI가 작동하는 프로세스는 다음과 같다.

1. request를 받으면
2. CGI 프로세스가 생성되고
3. 메모리를 로딩하고
4. 로직을 처리하고
5. 종료한다.

##### Fast CGI
CGI의 경우 요청이 정해져있는 경우가 많아 비슷하게 쓰이는 자원이 많다.
하나의 요청에 대해 생성과 종료가 이루어지는 것은 불필요한 낭비.
하나의 프로세스가 여러 요청을 여러 쓰레드에 담당시켜 처리할 수 있도록 한다.
메모리를 공유하게 되므로 명령이 절약되어 처리속도가 빨라진다.

**Comment by jeuxdeau** [comment]
SSL https://opentutorials.org/course/228/4894
CA 비밀키 털려서 허위 인증서 돌아다녀서 파산한 사례
https://www.boannews.com/media/view.asp?idx=27739
