### ISSUE TITLE
9장 웹 로봇 질문

### ISSUE THREAD

**Issue by mgcation** [jeuxdeau/http-the-definitive-guide#31]
# 웹 로봇
## 질문 리스트
- 코멘트로 남기기

## 이번 주 공지
- 말씀드린 대로 수요일에 함당 (월요일 저 점검ㅠㅠㅜ 화요일 일띢 운동~💪)
- 크리스마스 주 쉽니다 (자훈이형 애인들이랑 해외로 놀러감 😎)
- 12/30 ~ 1/3 오또케? (30일 1챕터 vs 조금미뤄서 2일에 두챕터) 어때여
  > 만나서 이야기 하시져

**Comment by mgcation** [comment]
### 로봇이 방문한 URL 탐색을 위해 사용하는 자료구조 중 트리는 어떤식으로 이뤄져 있을까?
- 트리 깊이가 무엇을 기준으로 형성되는지?
  - 도메인 레벨?
- URL 탐색 등과 같이 대용량, 고 중첩 가능성 모델을 트리로 만들 때 어떤 점을 유의해야 하는지 알 수 있다면 이것도 알아보기?

### 만약 웹페이지 컨텐츠가 browser history 에 종속적이라면 (script 파일에 종속적이라면) 크롤러는 이에 대해 무방비 상태가 될까?
- 그렇다면, 크롤러가 무방비되는 경우는?
  -  (=SEO에 악영향을 미치는 경우) 가 어느어느 것이 있을까?
- 로봇은 첫 로드되는 html 파일에 대해서만 크롤링할까?
  - js에 의해 웹이 상당히 의존하고 있다면?
    - (시시각각 변하거나, 링크를 동적으로 생성하거나)
    - 만약 스크립트 의존 문제를 해결하지 못한다면 robots.txt 로 커버할 수 있을까?
    - 웹 페이지 설계부터가 잘못된걸까?

### 사악한 웹 마스터가 로봇을 함정에 빠트릴 수 있는 함정들은 무엇들이 있을까?
- 책에서 소개된 동적 웹 생성 말고 다른 예시가 있다면

### 사적 용도(서치엔진이 아닌데도)로 로봇을 사용해도 되는가?
- 허용된다면, 그 기준은 어디까지인가?
- 사적 용도로 사용되는 경우는, `특정 호스트의 doc root를 기준으로 크롤링 또는 브루트 포스 크롤링하여 개인이 특수 목적을 가지고 사용`을 지칭하게 될 것 같음
- 관련 법적 문제에 대해 큰 이슈가 있다면 찾아보기

**Comment by jeuxdeau** [comment]
다음주에 자훈님 빼고 하자는 의견입니다.진도가 너무 느려요 i think~~

**Comment by mgcation** [comment]
일단 저 월욜 회식 화욜 리모투ㅜ

**Comment by digression99** [comment]
거우거우~

**Comment by jeuxdeau** [comment]
q. md5 메시지 요약 함수
a.
- md는 message disgest의 약자이다. md 함수는 해시 함수의 일종인데, f(원본 메시지) = (해당 메시지의 요약)인 것.
- 원본 메시지는 임의의 길이를 가질 수 있지만, 요약인 해시값은 고정 크기를 갖는다.
- md 계열 함수들은 Rivest라는 사람이 만들었으며, md2, md4, md5를 거쳐서 발전했다.
  - SHA(Secure Hash Algorithm, 안전한 해시 알고리즘)함수들 역시 md4에 기반한다.
- md2는 초기의 8비트 컴퓨터에 최적화되어 있는 8비트 버전이고, md4, md5는 32비트에 최적화되어 있다.
- 현재는 md5 알고리즘의 암호학적 취약성이 발견되었기 때문에, SHA-1과 같은 다른 알고리즘을 사용할 것이 권장된다.
- 자세한 알고리즘의 동작은 위키백과를 참고할 것.

> ref: 정보통신용어기술해설 http://www.ktword.co.kr/abbr_view.php/abbr_view.php?nav=2&id=960&m_temp1=1071
> ref: 위키백과 https://ko.wikipedia.org/wiki/MD5

q. 가상 호스팅 문제에서 - 요청 URI로도 어떤 docroot에 접근해야 할지 구분할 수 있는 것 아닌가? 왜 무조건 디폴트 루트로 가게 되는 것인가?
=> URI에 대한 요청은 DNS 뒤져서 ip 주소로 날아가기 때문.

q. 로봇용 페이지 보여주는 개념 따로 있었던 것 같은데... user agent에 따라서 성능상 더 낫게 하기 위해 아예 다른 페이지로 리다이렉션(?) 시켜주는 개념(?) 뭐라고 검색해야 할지 모르겠다.
=> headless browser

> ref: https://beomi.github.io/gb-crawling/posts/2017-09-28-HowToMakeWebCrawler-Headless-Chrome.html

q. 구글 랭킹 알고리즘?
a.
> ref: Google의 페이지 랭크 알고리즘 https://sungmooncho.com/2012/08/26/pagerank/

- 기본적인 개념은 논문처럼 피인용수가 높으면 그 페이지는 좋은 페이지라고 생각하는 것이다.
- 단순히 피인용 숫자만 더한다고 생각해보자. Rank(특정 페이지) = Rank(특페를 인용한 페이지1) + Rank(특페를 인용한 페이지2) + Rank(너무 길다 페이지3) + ... Rank(페이지n).
- 어떤 논문은 논문 1000개를 인용할 수도 있고, 어떤 논문은 논문 1개만 인용했을 수도 있다. 그런데도 각각의 인용 1개가 같은 가중치를 가지나? 아니다.
- Rank를 정규화한다. 정규화한다는 것은 Rank(페이지) / (해당 페이지가 인용한 페이지 갯수) (이걸 F(페이지)라고 하자)
- 랭킹이 높은 페이지들이 인용을 많이 할수록 해당 페이지도 랭킹이 올라간다.
- 식이 Rank(특정 페이지) = F(걔 인용한 다른 페이지) + F(다른 페이지2) + ... + F(다른 페이지3)
- 근데 사람들이 무한히 클릭만 하고 있지는 않고, 언젠가는 만족하고 멈추지 않는가? 그니까 그 페이지에 링크가 걸려 있어도 꼭 누르지 않을 수도 있다. 그래서 링크 누를 확률인 damping factor라는 것을 곱해준다. (ref 참고)

사족.
https://blog.npcode.com/2015/06/07/%EC%9B%B9-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EB%A5%BC-%EC%9C%84%ED%95%9C-http-%EC%99%84%EB%B2%BD-%EA%B0%80%EC%9D%B4%EB%93%9C-%EC%9D%BD%EB%8A%94-%EB%B2%95/

**Comment by 0pg** [comment]
Q. 9.1.5
- 느슨한 존재 비트맵
설명만으론 해시 테이블과 크게 다른 것 같지 않은데..

Q. 9.1.10
- URL 정규화
크롤러는 웹 서버가 가상 호스팅을 지원하는지, IP 주소가 같은 장비를 가리키는지 등의 정보를 어떻게 알 수 있나?
- 콘텐츠 지문
페이지 콘텐츠에서 어느 정도 크기의 바이트를 얻어오고 또 어떻게 생성?

Q. 9.4.2
- 웹 사이트와 robots.txt 파일들
현재현재는 가상호스팅 환경에서 로컬 robots.txt 파일을 개별 서브디렉터리에 설치할 수 있나?

**Comment by jeuxdeau** [comment]
===오늘회의===
1. 질문1개이상

**Comment by jeuxdeau** [comment]
https://prolite.tistory.com/1461 티스토리 메타 태그

**Comment by jeuxdeau** [comment]
robots.txt 401, 403 나왔을때 처리를 어떻게 하는게 표준인가?
