### ISSUE TITLE
ch 14. 보안 HTTP

### ISSUE THREAD

**Issue by digression99** [jeuxdeau/http-the-definitive-guide#39]

**Comment by jeuxdeau** [comment]
# HTTPS connections over proxy servers
https://stackoverflow.com/questions/516323/https-connections-over-proxy-servers

### CONNECT 메소드 사용
* CONNECT 메소드를 사용해 HTTP를 TCP로 변환해 TCP 커넥션을 수립
* 프록시가 요청/응답을 읽거나, 수정하거나, 캐싱할 수 없음

### 중간자(man in the middle)
1. 클라이언트가 HTTPS 연결을 시작한다.
2. 프록시가 커넥션을 인터셉트하고, 임시 인증서를 발급한다. 단 이 인증서에는 클라이언트가 무조건적으로 신뢰하는 서명이 있어야 한다.
3. 프록시가 타겟 서버와의 HTTPS 연결을 시작한다.
4. 프록시가 SSL 인증서의 무결성을 검사한다. 만약 유효하지 않은 인증서인 경우 에러를 표시한다.
5. 프록시가 임시 인증서를 통해 암호화/복호화하며 요청/응답을 스트리밍한다.

- 즉 클라이언트-프록시, 프록시-서버의 이중 연결이 생기는 것
- 클라이언트는 실제 서버와 통신하고 있지 않다는 응답을 받을 수 있음
- 프록시가 요청/응답 정보를 읽을 수 있음
- 서버와 클라이언트 사이에 도청자(eavesdroppers)가 없어야 한다는 TLS/SSL의 원칙과는 맞지 않는 접근 방법

### SOCKS
OSI 레이어 5(between the  [presentation layer](https://en.wikipedia.org/wiki/Presentation_layer)  and the  [transport layer](https://en.wikipedia.org/wiki/Transport_layer) )에 위치한 [SOCKS (Wikipedia)](https://en.wikipedia.org/wiki/SOCKS) 프록시 사용

**Comment by digression99** [comment]
## RSA는 어떻게 동작할까?
