### ISSUE TITLE
15장 엔터티와 인코딩

### ISSUE THREAD

**Issue by jeuxdeau** [jeuxdeau/http-the-definitive-guide#40]
@digression99 
1. brotli 정리
2. 오프라인 질문 정리

@jahun-kim 
1. HLS / LHLS 정리

**Comment by 0pg** [comment]
## 특별한 목적을 가진 chunked transfer encode 사용 예 - HLS 와 LHLS
### HLS 란?
* HLS는 HTTP Live Streaming 의 약자로 Apple 에서 만든 비디오 전송 프로토콜
* 크게 playlist 인 m3u8 파일과 각각의 미디어 세그멘트 파일로 구성된다
* live streaming 시 client player 는 m3u8 playlist 에 명시되어있는 미디어 세그멘트 파일을 요청해 재생하며 동시에 m3u8 playlist 도 주기적으로 요청해 갱신한다
    * m3u8 파일 내용 예
![image](https://user-images.githubusercontent.com/26541672/75113734-8af95a00-5693-11ea-8212-daee81b00b0b.png)
* HLS 에서 송출자가 보낸 영상을 시청자가 보기 위해선 위 사진에서 볼 수 있듯이 서버에서 미디어 세그멘트 파일을 생성하고, m3u8 에 업데이트 한 후 시청 클라이언트가 갱신된 m3u8 파일을 받아가 생성되니 미디어 세그멘트 파일을 요청해야 한다
    * 그만큼 송출/시청 영상 사이의 딜레이가 발생 (player buffer 와 같은 다른 지연 요소들을 고려하지 않더라도)

### LHLS (Low Latency HLS, twitch 에서 사용중인 HLS protocol 확장, Apple 에서 정의한 Low Latency HLS - LLHLS 와는 전혀 다름)
* HLS 에서의 송출/시청 간 딜레이를 줄여보기 위해 개선된 프로토콜
* 아직 완성되지 않은(file stream 이 아직 닫히지 않은) 미디어 세그멘트를 m3u8 에 추가
* 아직 만들어지지 않은 (file stream 이 아직 생성되지 않은) 미디어 세그먼트를 m3u8 에 추가
![image](https://user-images.githubusercontent.com/26541672/75113947-7e760100-5695-11ea-8ca7-2716f8c73914.png)
* client 는 생성중인 미디어 세그멘트 파일을 transfer-encode : chunked 를 통해 실시간으로 생성되는 파일을 받아와 미디어 세그멘트 파일 생성을 기다리는 시간만큼 딜레이를 줄일 수 있다

**Comment by digression99** [comment]
## Offline questions

* Q. chunked encoding일 시, content length가 없으므로 캐시가 무시되는가?
* Q. content length를 클라이언트에서 문제가 발생했는지 어떻게 검증할 수 있을까.
* Q. content length는 왜 잘못 계산되는걸까.
* Q. 엔터티 헤더 vs 메시지 헤더?

**Comment by jeuxdeau** [comment]
@digression99 
너무 오래 돼서 일단 이슈는 닫습니다 ㅎㅎ 업데이트할 내용 있으시면 [여기에 바로 푸시해 주세요](https://github.com/jeuxdeau/http-the-definitive-guide/blob/master/iv.entities-encodings-and-internationalization/15.entities-and-encodings/15.entities-and-encodings-qna.md)
