### ISSUE TITLE
4장 질문 : 커넥션 관리

### ISSUE THREAD

**Issue by mgcation** [jeuxdeau/http-the-definitive-guide#9]
[3명이 3개 이상의 질문을 선별하고 6개의 질문을 투표로 정합니다.](https://jeuxdeau.gitbook.io/http-the-definitive-guide/i.http-the-webs-foundation/meeting-minutes#10-22)
> 4개 또는 9개인데 일단 임의로 4개로 선별하였습니다

- [ ] TCP 데이터 조각이 0인 경우는 어떤 경우일까? (0)
- [ ] bind()와 listen()을 한번에 쓰면 안되나? (0)
- [x] 하나의 포트로 수 많은 클라이언트의 연결을 받기 위해 사용하는 전략은 무엇무엇이 있을까? (2)
- [x] 한 TCP 소켓은 어떻게 동시에 read / write 할 수 있을까? (2)
- [x] http/2 와 http/3 는 커넥션을 어떻게 관리할까?(4)
- [ ] 새로운 커넥션이 이미 사용한 커넥션(TIME_WAIT에 걸려있는 커넥션)이 아니라는 보장을 어떻게 할까? (0)
- [ ] persistent connection, keep-alive는 무엇이며 어떤 상황에서 활용할까? (1)
- [ ] hop-by-hop header는 무엇이고 어떻게 다뤄야 할까? (1)
- [ ] TCP handshake는 SYN/ACK을 활용하는데, 패킷이 작다. 이에 대한 최적화 전략이 있을까? (1)
- [x] http/2의 다중(multiplexed) 커넥션에 대해 알아보자 (4)
- [ ] 커넥션 헤더(http 필드명 / 임시적인 토큰 값 / close 값)에 대해 알아보자 (1)
- [ ] chunked transfer encoding 이 무엇일까? (1)

**Comment by jeuxdeau** [comment]
마지막 2개가 조금 겹치는 것 같네요

**Comment by jeuxdeau** [comment]
**오프에서 나온 질문**
1. 병렬 커넥션에서 대역폭이 좁을 때 전송 속도가 느려지는 정확한 이유?
2. (UX 측면에서) 여러 리소스를 병렬로 받아오는 게 더 나은거? 어떻게 나은가?
3. chunked transfer encoding
4. 다음 proxy가 connection을 구현하고 있는지 어떻게 아나?
5. 지속 커넥션 2개 제한은 무슨 기준?

**기타**
- 스터디 강사비 지원 신청하기

**Comment by 0pg** [comment]
나는 바보다

**Comment by jeuxdeau** [comment]
@digression99 @mgcation 
PR

@jahun-kim 
http/3 캐싱 질문 업데이트 부탁
